[package]
name = "classifier"
version = "0.1.0"
authors = ["Jeff Larson <thejefflarson@gmail.com>"]

[dependencies]
murmurhash3 = "^0.0.5"
regex = "^0.2"
rusty-machine = "^0.5.4"
serde = "^1.0.11"
serde_derive = "^1.0.9"
serde_json = "^1.0.2"
server = { path = "../server" }
