[package]
name = "server"
version = "0.1.0"
authors = ["Jeff Larson <thejefflarson@gmail.com>"]

[dependencies]
chrono = "^0.4.0"
diesel = { version = "^0.16", features = ["postgres", "chrono"] }
diesel_codegen = { version = "^0.16", features = ["postgres"] }
dotenv = "^0.10.1"
futures = "^0.1.15"
futures-cpupool = "^0.1.5"
hyper = "^0.11.2"
hyper-tls = "^0.1.2"
kuchiki = "^0.5.1"
log = "^0.3.8"
log4rs = "^0.7.0"
r2d2 = "^0.7.3"
r2d2-diesel = "^0.16.0"
rusoto_core = "^0.28.0"
rusoto_credential = "^0.8.0"
rusoto_s3 = "^0.28.0"
serde = "^1.0.11"
serde_json = "^1.0.2"
serde_derive = "^1.0.9"
tokio-core = "^0.1.9"
classifier = { path = "../classifier" }